
---
root    : true
extends : "coremail"

# override eslint-config-standard
parserOptions:
    ecmaVersion : 5
    ecmaFeatures:
        experimentalObjectRestSpread: false
        jsx: false
    #sourceType: "script"

env:
    amd                             : true
    browser                         : true
    jasmine                         : true

globals:
    $                               : true
    jQuery                          : true
    requirejs                       : true
    jasmineRequire                  : true
    ActiveXObject                   : true
    # Globals from Coremail Webmail
    CM                              : true
    CC                              : true
    KindEditor                      : true

rules:
    eqeqeq                          : warn
    keyword-spacing                 : warn
    space-before-blocks             : warn
    padded-blocks                   : off
